name: gears_env2
channels:
  - bioconda
  - conda-forge
  - r
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.6.2=hbcca054_0
  - ld_impl_linux-64=2.40=hf3520f5_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h77fa898_7
  - libgomp=13.2.0=h77fa898_7
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.45.3=h2797004_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=h4ab18f5_1
  - ncurses=6.5=h59595ed_0
  - openssl=3.3.0=h4ab18f5_3
  - pip=24.0=pyhd8ed1ab_0
  - python=3.10.14=hd12c33a_0_cpython
  - readline=8.2=h8228510_1
  - setuptools=70.0.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tzdata=2024a=h0c530f3_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xz=5.2.6=h166bdaf_0
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - anndata==0.10.7
      - array-api-compat==1.7.1
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - cell-gears==0.1.2
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - comm==0.2.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - dcor==0.6
      - debugpy==1.8.1
      - decorator==5.1.1
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - filelock==3.14.0
      - fonttools==4.53.0
      - frozenlist==1.4.1
      - fsspec==2024.6.0
      - h5py==3.11.0
      - idna==3.7
      - ipykernel==6.29.4
      - ipython==8.25.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - kiwisolver==1.4.5
      - legacy-api-wrap==1.4
      - llvmlite==0.42.0
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - multidict==6.0.5
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - numba==0.59.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.40
      - nvidia-nvtx-cu12==12.1.105
      - packaging==24.0
      - pandas==2.2.2
      - parso==0.8.4
      - patsy==0.5.6
      - pexpect==4.9.0
      - pillow==10.3.0
      - platformdirs==4.2.2
      - prompt-toolkit==3.0.45
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.18.0
      - pynndescent==0.5.12
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyzmq==26.0.3
      - requests==2.32.3
      - scanpy==1.10.1
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - session-info==1.0.0
      - six==1.16.0
      - stack-data==0.6.3
      - statsmodels==0.14.2
      - stdlib-list==0.10.0
      - sympy==1.12.1
      - threadpoolctl==3.5.0
      - torch==2.3.0
      - torch-geometric==2.5.3
      - tornado==6.4
      - tqdm==4.66.4
      - traitlets==5.14.3
      - triton==2.3.0
      - umap-learn==0.5.6
      - urllib3==2.2.1
      - wcwidth==0.2.13
      - yarl==1.9.4
prefix: /g/huber/users/ahlmanne/conda-envs/gears_env2
